project:
  type: website

website:
  title: "Dr. Julian Barg, climate disinformation research"
  navbar:
    right:
      - text: "Publications"
        menu:
          - text: Montgomery et al. (2021) No End in Sight? A Greenwash Review and Research Agenda
            href: https://journals.sagepub.com/doi/10.1177/10860266231168905
          - text: Zbaracki et al (2021)
            href: content/zbaracki_et_al_2021.qmd
      - about.qmd
      - text: "![](/resources/bsky.png){height=1em}"
        href: https://bsky.app/profile/jbarg.bsky.social
      - icon: linkedin
        href: https://www.linkedin.com/in/julian-barg/
      - icon: github
        href: https://github.com/julianbarg/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



